### ISSUE TITLE
Reposense issue

### ISSUE THREAD

**Issue by okkhoy** [CS2113-AY1819S1-T13-4/main#131]
When I run Reposense, I get this error on the log. 
 >`CS2113-AY1819S1-T13-4_main_master/_reposense/config.json is malformed.`

Your team's contributions _may_ not be recognized correctly. 
Please fix the issue soon and let me know

-Akshay

**Comment by novin997** [comment]
I have updated the Config.Json to the following code. Please help to run reposense and if it is working now. Thank you.

![image](https://user-images.githubusercontent.com/35754514/47987496-9c26fc00-e11a-11e8-8409-aec318d527a0.png)

**Comment by okkhoy** [comment]
Your updated version seems correct. You need to escape the `\` as it is an escape character itself!

Question: Did you run reposense locally with the updated config? If it shows the contributions correctly and doesn't throw errors in the log, you are good to go.

Reposense will pick up the correct config when I run it next.

**Comment by novin997** [comment]
The local copy is working and it seems to include my previous commits. Thank you for your help

![image](https://user-images.githubusercontent.com/35754514/47992207-4016a480-e127-11e8-8c02-de9a41f9c888.png)
