### ISSUE TITLE
Fix help Command in Student Mangement Issue

### ISSUE THREAD

**Issue by novin997** [CS2113-AY1819S1-T13-4/main#52]

**Comment by rajdeepsh** [comment]
The window shown from the help command is from a html file under /docs. This is not the user guide file, hence the windows content wont be updated with respect to the user guide. To edit the help window's content , we have to edit the content under the HelpWindow.html file.

**Comment by E0176882** [comment]
To solve the issue, go to terminal and type gradlew deployOfflineDocs
